ktor:
  application:
    modules:
      - ru.miet.kvosk.notes.ApplicationKt.module
  deployment:
    port: "$APP_PORT:8080"

app:
  env: "$APP_ENV:local"

db:
  host: "$DB_HOST:localhost"
  port: "$DB_PORT:5432"
  name: "$DB_NAME:notes"
  user: "$DB_USER:notes"
  password: "$DB_PASSWORD:notes"
